### ISSUE TITLE
Gradle sync failed: For input string: ""     

### ISSUE THREAD

**Issue by XuanQinjian** [lovejjfg/PowerRecyclerView#1]
initMinshengGradleEnvironment()
ext {
    gitTag = 'git describe --tags'.execute([], project.rootDir).text.trim()
    gitCommitCount = 100 +
            Integer.parseInt('git rev-list --count HEAD'.execute([], project.rootDir).text.trim())
}

parseInt报空了   我随便改了个“20”

**Comment by lovejjfg** [comment]
谢谢指出这个问题，在首次导入 `AndroidStudio`, 但是还没有引入`git root`的时候会产生这个问题，另外如果 `git/bin` 没有添加到环境变量 `path` 里面会出现` Error:CreateProcess error=2, 系统找不到指定的文件。`的错误，解决方案建议按照上面步骤两个都设置好，要么简单粗暴的就是直接改一个默认数字就好了。

**Comment by letuszou** [comment]
看不明白呀
Error:CreateProcess error=2

**Comment by lovejjfg** [comment]
上面不是解释了的吗？你需要将 `git` 的路径添加到 `path` 环境变量中。
